# Auto generated 
"""updates inventory and shipment models

Revision ID: 01af7c34cf07
Revises: 03160cca2033
Create Date: 2022-01-17 20:05:34.582320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01af7c34cf07'
down_revision = '03160cca2033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'shipment', ['shipment_id'], ['id'])
    op.drop_column('inventory', 'total_quantity')
    op.add_column('shipment', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'address')
    op.add_column('inventory', sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'shipment_id')
    op.drop_column('inventory', 'quantity')
    # ### end Alembic commands ###
