# Auto generated 
"""empty message

Revision ID: 1a60cd91ff95
Revises: fcaf9743436e
Create Date: 2022-01-19 20:01:10.168002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a60cd91ff95'
down_revision = 'fcaf9743436e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('shipment', sa.Column('breath', sa.Float(), nullable=True))
    op.add_column('shipment', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('shipment', sa.Column('name', sa.String(), nullable=True))
    op.add_column('shipment', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('shipment', sa.Column('width', sa.Float(), nullable=True))
    op.drop_column('shipment', 'received_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('received_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('shipment', 'width')
    op.drop_column('shipment', 'weight')
    op.drop_column('shipment', 'name')
    op.drop_column('shipment', 'length')
    op.drop_column('shipment', 'breath')
    op.drop_column('inventory', 'price')
    # ### end Alembic commands ###
