# Auto generated 
"""makes changes to inventory model

Revision ID: 529b8d2bc434
Revises: c1874aa52c80
Create Date: 2022-01-16 14:55:44.086814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529b8d2bc434'
down_revision = 'c1874aa52c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'name')
    # ### end Alembic commands ###
