# Auto generated 
"""adds created date to shipment

Revision ID: fcaf9743436e
Revises: 01af7c34cf07
Create Date: 2022-01-17 20:12:53.873245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaf9743436e'
down_revision = '01af7c34cf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('shipment', sa.Column('received_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'received_date')
    op.drop_column('shipment', 'created_date')
    # ### end Alembic commands ###
